steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '3.9.0'
      installKubectl: true

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'k8s-sa-ca'
      command: 'package'
      chartPath: './mychart'
      updateDependency: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'charts'
      publishLocation: 'Container'

  - task: HelmDeploy@0
    displayName: 'helm upgrade'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'k8s-sa-ca'
      command: upgrade
      arguments: '--atomic --debug'
      chartType: FilePath
      chartPath: '$(Build.ArtifactStagingDirectory)/mychart-0.1.0.tgz'
      releaseName: 'nginx-$(goal)'
      valueFile: 'mychart/values/nginx-$(goal).yml'
      overrideValues: "goal=$(goal)"
